@url=http://localhost:8086

### CLIENTES

### Cria um novo cliente
POST {{url}}/clientes
Content-Type: application/json

{
    "nome": "Zé Trovão dos Ventos",
    "cpf": "42542642750",
    "telefone": "44996060606",
    "endereco": "Estrada Tempestade, 2507",
    "email": "ze.trovao105@gmail.com",
    "senha": "senhaZe105"  
}

### Busca todos os clientes
GET {{url}}/clientes

### Busca um cliente específico pelo id
GET {{url}}/clientes/357c8684-ef54-4572-a5bc-57d03039f323

### Atualiza um cliente específico pelo id
PUT {{url}}/clientes/398fe6b0-9441-4d53-9fb3-60b90c0d7ad2
Content-Type: application/json

{
    "nome": "João Martins",
    "cpf": "12345678900",
    "telefone": "44912345678",
    "endereco": "Rua das Flores, 321",
    "email": "joaomartins@gmail.com",
    "senha": "senhaSegura123"
}

### Deleta um cliente específico pelo id
DELETE {{url}}/clientes/9eb6ec56-53b6-40eb-8fbe-e26a5febc2d7


### FUNCIONÁRIOS
### Cria um novo funcionario
POST {{url}}/funcionarios
Content-Type: application/json

{
    "nome": "Fabiana da Silva",
    "cpf": "98745621348",
    "cargo": "Atendente",
    "login": "fabi14@gmail.com",
    "senha": "senhaFabi14"  
}

### Busca todos os funcionarios
GET {{url}}/funcionarios

### Busca um funcionario específico pelo id
GET {{url}}/funcionarios/ead3b58c-eecc-477e-b009-555c7507fb6f

### Atualiza um funcionario específico pelo id
PUT {{url}}/funcionarios/ead3b58c-eecc-477e-b009-555c7507fb6f
Content-Type: application/json

{
    "nome": "Luciana Pereira",
    "cpf": "12365478955",
    "cargo": "Gerente",
    "login": "pereiraluciana23@gmail.com",
    "senha": "senhaSegura123"
}

### Deleta um funcionario específico pelo id
DELETE {{url}}/funcionarios/ead3b58c-eecc-477e-b009-555c7507fb6f


### CATEGORIAS DE CARROS
### Cria uma nova categoria de carro
POST {{url}}/categorias
Content-Type: application/json

{
    "nome_categoria": "SUV",
    "valor_diaria": 300.00
}

### Busca todos os categorias
GET {{url}}/categorias

### Busca um categoria específico pelo id
GET {{url}}/categorias/54450873-8284-4609-a8c0-fd52f242db02

### Atualiza um categoria específico pelo id
PUT {{url}}/categorias/54450873-8284-4609-a8c0-fd52f242db02
Content-Type: application/json

{
    "nome_categoria": "Econômico",
    "valor_diaria": 150.00
}

### Deleta um categoria específico pelo id
DELETE {{url}}/categorias/de45ba4b-6ede-404d-beff-f5f790e484a2

### CARROS

### Cria um novo carro
POST {{url}}/carros
Content-Type: application/json

{
  "id_categoria": "8f0dc1aa-e637-483a-ab78-b6498f14bc32",
  "imagem_carro": "imagem_url_exemplo.jpg",
  "placa": "ABC1234",
  "modelo": "Fiat Uno",
  "ano": 2015,
  "cor": "Branco",
  "status": "disponivel",
  "quilometragem_atual": 120000
}

### Busca todos os carros
GET {{url}}/carros

### Busca um carro específico pelo id
GET {{url}}/carros/

### Atualiza um carro específico pelo id
PUT {{url}}/carros/
Content-Type: application/json

{
    
}

### Deleta um carro específico pelo id
DELETE {{url}}/carros/

### LOCAÇÕES

### Cria uma nova locação
POST {{url}}/locacoes
{
    "id_cliente": "357c8684-ef54-4572-a5bc-57d03039f323",
    "id_carro": "9875b461-11d1-4c63-838b-67cbe71a1079",
    "id_funcionario": "ead3b58c-eecc-477e-b009-555c7507fb6f",
    "data_retirada": "2025-11-30T10:00:00.000Z",
    "data_devolucao_prevista": "2025-12-02T10:00:00.000Z",
    "valor_unitario": 200.00,
    "descricao": "Cliente retirou o carro sem observações."
}

### Busca todas as locações
GET {{url}}/locacoes

### Busca uma locação específica pelo id
GET {{url}}/locacoes/

### Atualiza uma locação específica pelo id
PUT {{url}}/locacoes/
Content-Type: application/json

{
    
}

### Deleta uma locação específica pelo id
DELETE {{url}}/locacoes/