@url=http://localhost:8086

### CLIENTES

### Cria um novo cliente
POST {{url}}/clientes
Content-Type: application/json

{
    "nome": "Zé Trovão dos Ventos",
    "cpf": "42542642750",
    "telefone": "44996060606",
    "endereco": "Estrada Tempestade, 2507",
    "email": "ze.trovao105@gmail.com",
    "senha": "senhaZe105"

   
}

### Busca todos os clientes
GET {{url}}/clientes

### Busca um cliente específico pelo id
GET {{url}}/clientes/357c8684-ef54-4572-a5bc-57d03039f323

### Atualiza um cliente específico pelo id
PUT {{url}}/clientes/398fe6b0-9441-4d53-9fb3-60b90c0d7ad2
Content-Type: application/json

{
    "nome": "João Martins",
    "cpf": "12345678900",
    "telefone": "44912345678",
    "endereco": "Rua das Flores, 321",
    "email": "joaomartins@gmail.com",
    "senha": "senhaSegura123"
}

### Deleta um cliente específico pelo id
DELETE {{url}}/clientes/9eb6ec56-53b6-40eb-8fbe-e26a5febc2d7

### CARROS

### Cria um novo carro
POST {{url}}/carros
Content-Type: application/json

{
 
}

### Busca todos os carros
GET {{url}}/carros

### Busca um carro específico pelo id
GET {{url}}/carros/

### Atualiza um carro específico pelo id
PUT {{url}}/carros/
Content-Type: application/json

{
    
}

### Deleta um carro específico pelo id
DELETE {{url}}/carros/